# Generated by Django 3.1.7 on 2021-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Receipt_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HSAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsan_id', models.IntegerField()),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=50)),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.IntegerField()),
                ('isapproved_site', models.CharField(default='N', max_length=3)),
                ('isapproved_master', models.CharField(default='N', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='material_master',
            name='Mid',
        ),
        migrations.AddField(
            model_name='material_master',
            name='category',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.AddField(
            model_name='material_master',
            name='desc',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.AddField(
            model_name='material_master',
            name='hsan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material_master',
            name='mat_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='material_master',
            name='unit',
            field=models.CharField(default='N', max_length=50),
        ),
    ]
