# Generated by Django 3.1.7 on 2021-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0002_auto_20210310_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_requisition',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
