# Generated by Django 3.1.7 on 2021-04-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0004_auto_20210405_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_id', models.CharField(max_length=50)),
                ('subcat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='material_master',
            old_name='category',
            new_name='cat_id',
        ),
        migrations.AddField(
            model_name='material_master',
            name='subcat_id',
            field=models.CharField(default='N', max_length=50),
        ),
    ]
