# Generated by Django 3.1.7 on 2021-04-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0005_auto_20210408_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_sub_category',
            name='cat_id',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
