# Generated by Django 3.1.7 on 2021-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0006_material_sub_category_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_sub_category',
            name='subcat_name',
            field=models.CharField(max_length=150),
        ),
    ]
