# Generated by Django 3.1.7 on 2021-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0007_auto_20210408_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_master',
            name='desc',
            field=models.CharField(default='N', max_length=250),
        ),
    ]
