# Generated by Django 3.1.7 on 2021-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0008_auto_20210408_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_requisition_details',
            old_name='col1',
            new_name='mat_id',
        ),
        migrations.RemoveField(
            model_name='purchase_requisition_details',
            name='col2',
        ),
        migrations.AddField(
            model_name='purchase_requisition_details',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
