# Generated by Django 3.1.7 on 2021-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0009_auto_20210411_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_requisition_details',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase_requisition_details',
            name='mat_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
