# Generated by Django 3.1.7 on 2021-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0010_auto_20210415_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_requisition_details',
            name='unit',
            field=models.CharField(default='N', max_length=50),
        ),
    ]
