# Generated by Django 3.1.7 on 2021-04-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0011_purchase_requisition_details_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(default='', max_length=200)),
                ('mat_name', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='N', max_length=50)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField()),
                ('project_name', models.CharField(default='', max_length=200)),
                ('delivery_loc', models.CharField(default='', max_length=200)),
                ('supp_id', models.IntegerField()),
                ('isapproved_master', models.CharField(default='N', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_id', models.IntegerField()),
                ('supp_name', models.CharField(default='', max_length=200)),
                ('supp_address', models.CharField(default='', max_length=200)),
                ('contact_person', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=15)),
                ('state', models.CharField(default='', max_length=30)),
                ('gst', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase_Order',
        ),
        migrations.AddField(
            model_name='purchase_order_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='mis_backend.purchase_order_mst', verbose_name='Header Ref ID'),
        ),
    ]
