# Generated by Django 3.1.7 on 2021-04-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0012_auto_20210416_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_mst',
            name='isapproved_master',
        ),
    ]
