# Generated by Django 3.1.7 on 2021-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0013_remove_purchase_order_mst_isapproved_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_details',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
