# Generated by Django 3.1.7 on 2021-04-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0014_auto_20210417_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_details',
            name='rate',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
