# Generated by Django 3.1.7 on 2021-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0015_auto_20210417_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase_Order_details',
        ),
        migrations.DeleteModel(
            name='Purchase_Order_mst',
        ),
    ]
