# Generated by Django 3.1.7 on 2021-04-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0016_auto_20210418_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField()),
                ('project_name', models.CharField(default='', max_length=200)),
                ('delivery_loc', models.CharField(default='', max_length=200)),
                ('supp_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(default='', max_length=200)),
                ('mat_name', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='N', max_length=50)),
                ('rate', models.CharField(default='0', max_length=50)),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='mis_backend.purchase_order_mst', verbose_name='Header Ref ID')),
            ],
        ),
    ]
