# Generated by Django 3.1.7 on 2021-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0017_purchase_order_details_purchase_order_mst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_details',
            name='rate',
            field=models.FloatField(),
        ),
    ]
