# Generated by Django 3.1.7 on 2021-04-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0018_auto_20210418_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order_details',
            old_name='rate',
            new_name='item_rate',
        ),
    ]
