# Generated by Django 3.1.7 on 2021-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0019_auto_20210418_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_details',
            name='complete',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AddField(
            model_name='purchase_order_mst',
            name='complete',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase_order_details',
            name='item_rate',
            field=models.FloatField(default=0),
        ),
    ]
