# Generated by Django 3.1.7 on 2021-04-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0020_auto_20210419_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Receipt_Note_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(default='', max_length=200)),
                ('mat_name', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('rec_quant', models.IntegerField(default=0)),
                ('unit', models.CharField(default='N', max_length=50)),
                ('item_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Receipt_Note_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_id', models.IntegerField()),
                ('po_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Goods_Receipt_Note',
        ),
        migrations.AddField(
            model_name='goods_receipt_note_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='mis_backend.goods_receipt_note_mst', verbose_name='Header Ref ID'),
        ),
    ]
