# Generated by Django 3.1.7 on 2021-04-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0021_auto_20210420_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(default='', max_length=200)),
                ('mat_name', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='N', max_length=50)),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='mis_backend.projects', verbose_name='Header Ref ID')),
            ],
        ),
    ]
