# Generated by Django 3.1.7 on 2021-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0022_stock_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=25)),
                ('admin', models.CharField(default='N', max_length=3)),
                ('pr', models.CharField(default='N', max_length=3)),
                ('pr_gm', models.CharField(default='N', max_length=3)),
                ('po', models.CharField(default='N', max_length=3)),
                ('grn', models.CharField(default='N', max_length=3)),
                ('challan', models.CharField(default='N', max_length=3)),
                ('stock', models.CharField(default='N', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=30)),
                ('role', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
