# Generated by Django 3.1.7 on 2021-05-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0025_projects_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.usermodel'),
        ),
    ]
