# Generated by Django 3.1.7 on 2021-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0027_auto_20210507_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='challan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='grn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='po',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='pr_gm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
