# Generated by Django 3.1.7 on 2021-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0028_auto_20210509_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
