# Generated by Django 3.1.7 on 2021-05-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0031_auto_20210513_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stock_details',
            name='project_id',
        ),
        migrations.AddField(
            model_name='stock_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='mis_backend.stock_mst', verbose_name='Header Ref ID'),
        ),
    ]
