# Generated by Django 3.1.7 on 2021-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0033_auto_20210513_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_mst',
            name='mat_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stock_mst',
            name='mat_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='stock_mst',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock_mst',
            name='recieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock_mst',
            name='unit',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.DeleteModel(
            name='Stock_details',
        ),
    ]
