# Generated by Django 3.1.7 on 2021-05-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0035_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.projects'),
        ),
        migrations.AlterField(
            model_name='stock_mst',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.projects'),
        ),
    ]
