# Generated by Django 3.1.7 on 2021-05-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0039_auto_20210519_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_requisition_mst',
            name='made_by',
        ),
    ]
