# Generated by Django 3.1.7 on 2021-05-19 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0041_purchase_requisition_mst_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_requisition_mst',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='purchase_requisition_mst',
            name='updated_date_time',
        ),
        migrations.AddField(
            model_name='purchase_requisition_mst',
            name='required_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
