# Generated by Django 3.1.7 on 2021-05-19 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0042_auto_20210519_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_requisition_details',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='purchase_requisition_details',
            name='updated_date_time',
        ),
        migrations.RemoveField(
            model_name='purchase_requisition_mst',
            name='required_date',
        ),
        migrations.AddField(
            model_name='purchase_requisition_details',
            name='required_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddField(
            model_name='purchase_requisition_mst',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time'),
        ),
        migrations.AddField(
            model_name='purchase_requisition_mst',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time'),
        ),
    ]
