# Generated by Django 3.1.7 on 2021-05-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0043_auto_20210519_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_requisition_details',
            name='required_date',
            field=models.DateTimeField(),
        ),
    ]
