# Generated by Django 3.1.7 on 2021-07-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0044_auto_20210519_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supp_id',
        ),
    ]
