# Generated by Django 3.1.7 on 2021-07-22 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0045_remove_supplier_supp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.CreateModel(
            name='Delivery_Challan_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_project', to='mis_backend.projects')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_project', to='mis_backend.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Challan_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(default='', max_length=200)),
                ('mat_name', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='N', max_length=50)),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='mis_backend.delivery_challan_mst', verbose_name='Header Ref ID')),
            ],
        ),
    ]
