# Generated by Django 3.1.7 on 2021-07-31 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0047_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req_Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(default='', max_length=200)),
                ('mat_name', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='N', max_length=50)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='File_Upload',
        ),
    ]
