# Generated by Django 3.1.7 on 2021-07-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0048_auto_20210731_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_limit',
            name='utilized',
            field=models.IntegerField(default=0),
        ),
    ]
