# Generated by Django 3.1.7 on 2021-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0049_req_limit_utilized'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='identifier',
            field=models.CharField(default='FFFF', max_length=5),
        ),
    ]
