# Generated by Django 3.1.7 on 2021-08-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0050_projects_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='identifier',
            field=models.CharField(max_length=5),
        ),
    ]
