# Generated by Django 3.1.7 on 2021-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0052_auto_20210804_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_requisition_details',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
