# Generated by Django 3.1.7 on 2021-08-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0053_auto_20210804_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_mst',
            name='supp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supp_id', to='mis_backend.supplier'),
        ),
    ]
