# Generated by Django 3.1.7 on 2021-08-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0055_auto_20210804_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_mst',
            name='project_name',
        ),
        migrations.AddField(
            model_name='purchase_order_mst',
            name='project_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='mis_backend.projects'),
        ),
        migrations.AlterField(
            model_name='purchase_order_mst',
            name='supp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssup_id', to='mis_backend.supplier'),
        ),
    ]
