# Generated by Django 3.1.7 on 2021-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0057_auto_20210804_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_requisition_mst',
            old_name='isapproved_site',
            new_name='completed',
        ),
    ]
