# Generated by Django 3.1.7 on 2021-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0058_auto_20210804_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_mst',
            name='po_id',
        ),
        migrations.AddField(
            model_name='purchase_order_mst',
            name='req_id',
            field=models.CharField(default='FFFF-0000', max_length=13),
        ),
    ]
