# Generated by Django 3.1.7 on 2021-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0060_auto_20210804_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_mst',
            name='po_id',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='purchase_requisition_mst',
            name='req_id',
            field=models.CharField(max_length=13),
        ),
    ]
