# Generated by Django 3.1.7 on 2021-08-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0065_auto_20210817_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_mst',
            name='delivery_loc',
        ),
    ]
