# Generated by Django 3.1.7 on 2021-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0066_remove_purchase_order_mst_delivery_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_mst',
            name='other_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_order_mst',
            name='transport',
            field=models.FloatField(default=0),
        ),
    ]
