# Generated by Django 3.1.7 on 2021-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0069_req_limit_hsn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_details',
            name='hsn_id',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase_requisition_details',
            name='hsn_id',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
