# Generated by Django 3.1.7 on 2021-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0070_auto_20210820_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_id', models.CharField(max_length=10)),
                ('tax_rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='purchase_order_details',
            name='hsn_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase_requisition_details',
            name='hsn_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='req_limit',
            name='hsn_id',
            field=models.CharField(max_length=10),
        ),
    ]
