# Generated by Django 3.1.7 on 2021-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0071_auto_20210820_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsn',
            name='tax_rate',
            field=models.CharField(max_length=6),
        ),
    ]
