# Generated by Django 3.1.7 on 2021-08-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0073_purchase_order_details_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_receipt_note_mst',
            name='challan_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='goods_receipt_note_mst',
            name='supp_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ssup_id_grn', to='mis_backend.supplier'),
        ),
        migrations.AddField(
            model_name='goods_receipt_note_mst',
            name='vehicle_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='goods_receipt_note_mst',
            name='po_id',
            field=models.ForeignKey(default='40', on_delete=django.db.models.deletion.CASCADE, related_name='po_id_grn', to='mis_backend.purchase_order_mst'),
        ),
        migrations.AlterField(
            model_name='goods_receipt_note_mst',
            name='project_id',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, related_name='project_id_grn', to='mis_backend.projects'),
        ),
    ]
