# Generated by Django 3.1.7 on 2021-08-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0075_auto_20210823_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_receipt_note_mst',
            name='po_id',
            field=models.CharField(max_length=13),
        ),
    ]
