# Generated by Django 3.1.7 on 2021-08-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0076_auto_20210823_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_receipt_note_details',
            name='accepted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goods_receipt_note_details',
            name='hsn_id',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='goods_receipt_note_details',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goods_receipt_note_details',
            name='rec_quant',
            field=models.FloatField(default=0),
        ),
    ]
