# Generated by Django 3.1.7 on 2021-08-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0077_auto_20210825_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_receipt_note_details',
            name='hsn_id',
            field=models.CharField(max_length=10),
        ),
    ]
