# Generated by Django 3.1.7 on 2021-08-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0078_auto_20210825_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSAN',
        ),
        migrations.RemoveField(
            model_name='goods_receipt_note_details',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='goods_receipt_note_details',
            name='updated_date_time',
        ),
        migrations.RemoveField(
            model_name='purchase_order_details',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='purchase_order_details',
            name='updated_date_time',
        ),
        migrations.AddField(
            model_name='goods_receipt_note_mst',
            name='made_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase_order_mst',
            name='made_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
