# Generated by Django 3.1.7 on 2021-08-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0081_auto_20210826_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_limit',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='req_limit',
            name='utilized',
            field=models.FloatField(default=0),
        ),
    ]
