# Generated by Django 3.1.7 on 2021-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0082_auto_20210827_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
