# Generated by Django 3.1.7 on 2021-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0084_auto_20210831_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_challan_details',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
