# Generated by Django 3.1.7 on 2021-09-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0086_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req_limit',
            name='hsn_id',
        ),
        migrations.RemoveField(
            model_name='req_limit',
            name='mat_name',
        ),
        migrations.AlterField(
            model_name='req_limit',
            name='mat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='req_limit',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.projects', verbose_name='Projects'),
        ),
    ]
