# Generated by Django 3.1.7 on 2021-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0087_auto_20210917_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req_limit',
            name='unit',
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default='N', max_length=50),
        ),
    ]
