# Generated by Django 3.1.7 on 2021-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0088_auto_20210917_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
