# Generated by Django 3.1.7 on 2021-09-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0089_auto_20210917_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_mst',
            name='complete',
        ),
    ]
