# Generated by Django 3.1.7 on 2021-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0090_remove_purchase_order_mst_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_mst',
            name='po_id',
            field=models.CharField(max_length=14),
        ),
    ]
