# Generated by Django 3.1.7 on 2021-09-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0092_auto_20210920_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_details',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='purchase_order_mst',
            name='complete',
        ),
    ]
