# Generated by Django 3.1.7 on 2021-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0093_auto_20210920_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_details',
            name='complete',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AddField(
            model_name='purchase_order_mst',
            name='complete',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase_order_details',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
