# Generated by Django 3.1.7 on 2021-09-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0094_auto_20210920_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='mat_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='unit',
        ),
        migrations.AlterField(
            model_name='issue',
            name='mat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.material'),
        ),
    ]
