# Generated by Django 3.1.7 on 2021-09-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0096_remove_delivery_challan_details_mat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_challan_details',
            name='mat_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
