# Generated by Django 3.1.7 on 2021-09-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0097_delivery_challan_details_mat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_mst',
            name='mat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_backend.material', verbose_name='material'),
        ),
    ]
