# Generated by Django 3.1.7 on 2021-09-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0098_auto_20210921_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_limit',
            name='hsn_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='req_limit',
            name='mat_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='req_limit',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock_mst',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
