# Generated by Django 3.1.7 on 2021-09-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0099_auto_20210924_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_limit',
            name='hsn_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='req_limit',
            name='mat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='req_limit',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
