# Generated by Django 3.1.7 on 2022-01-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_backend', '0100_auto_20210924_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_details',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
